/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    user_created: string;
    user_updated: string;
    user_deleted: string;
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
