@baseUrl = http://localhost:27018
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5ZjQ0MDllYzM5ZTFjNGQ5ZTI1YTUiLCJpYXQiOjE3NDMzODU2NjQsImV4cCI6MTc0MzQ3MjA2NH0.u2plo7aBehlJJqhLpxmfRcAUYyS5svT8VSUXihVt0kw

### - Get all comments for admin
GET {{baseUrl}}/admin/comments
Content-Type: application/json
Authorization: {{token}}

### - Get all comments by post 
GET {{baseUrl}}/comments?postId=67ea0e79c71d0a25324bbcc1

### - Get one single comment
GET {{baseUrl}}/comment?_id=67ea11378e6c235ab1c40c46
Content-Type: application/json

### - Create comment 
POST {{baseUrl}}/comment
Content-Type: application/json
Authorization: {{token}}

{  
    "post": "67ea0e79c71d0a25324bbcc1",
    "text": "comment 02"
}

### - Update comment
Put {{baseUrl}}/comment
Content-Type: application/json
Authorization: {{token}}

{
    "_id": "67ea12f38e8b980d461294a6",
    "text": "124124"
}
  
### - Remove comment
DELETE  {{baseUrl}}/comment?_id=67ea12f38e8b980d461294a6
Content-Type: application/json
Authorization: {{token}} 