@baseUrl = http://localhost:27018
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4YTY4ZTUwMDEyMmQwNGU2NmUxNjIiLCJpYXQiOjE3NDMzNjg2MzcsImV4cCI6MTc0MzQ1NTAzN30.b6hdj--BiIm3TKaPS4Pmi2ufAh-CNjhskwNbOibCg1U

### - Get all users 
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: {{token}}

### - Get single user
GET {{baseUrl}}/user?_id=67e9f4409ec39e1c4d9e25a5
Content-Type: application/json
Authorization: {{token}}

### - Register user 
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "1",
    "phoneNumber": "+20 1214144124",
    "country": "egypt",
    "email": "1@gmail.com",
    "password": "123456"
}

### - Login user
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "5@gmail.com",
    "password": "123456"
}
 

 
 